version: '3'
services:
  app:
    image: ruby:2.6.8-alpine
    container_name: beelzebub
    tty: true
    stdin_open: true
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: ruby main.rb
